In [7]:
import pandas as pd

In [8]:
carbon_df = pd.read_csv('owid-co2-data.csv')

In [9]:
carbon_df

,iso_code,country,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,NaN,NaN,NaN,NaN,0.002,NaN,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,NaN,475.00,0.070,NaN,0.011,NaN,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,NaN,8.70,0.007,NaN,0.012,NaN,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,NaN,0.00,0.000,NaN,0.012,NaN,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001732e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,NaN,16.00,0.015,NaN,0.013,NaN,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25199,ZWE,Zimbabwe,2016,10.738,12.153,-12.17,-1.488,1.415,0.765,0.866,...,4.703,11.92,0.85,6.55,0.467,14030338.0,2.096179e+10,47.5,3385.574,1.889
25200,ZWE,Zimbabwe,2017,9.582,11.248,-10.77,-1.156,1.666,0.673,0.790,...,NaN,NaN,NaN,NaN,NaN,14236599.0,2.194784e+10,NaN,NaN,NaN
25201,ZWE,Zimbabwe,2018,11.854,13.163,23.72,2.273,1.308,0.821,0.912,...,NaN,NaN,NaN,NaN,NaN,14438812.0,2.271535e+10,NaN,NaN,NaN
25202,ZWE,Zimbabwe,2019,10.949,12.422,-7.64,-0.905,1.473,0.748,0.848,...,NaN,NaN,NaN,NaN,NaN,14645473.0,NaN,NaN,NaN,NaN
25203,ZWE,Zimbabwe,2020,10.531,NaN,-3.82,-0.418,NaN,0.709,NaN,...,NaN,NaN,NaN,NaN,NaN,14862927.0,NaN,NaN,NaN,NaN

In [10]:
carbon_df.dtypes

iso_code                                object
country                                 object
year                                     int64
co2                                    float64
consumption_co2                        float64
co2_growth_prct                        float64
co2_growth_abs                         float64
trade_co2                              float64
co2_per_capita                         float64
consumption_co2_per_capita             float64
share_global_co2                       float64
cumulative_co2                         float64
share_global_cumulative_co2            float64
co2_per_gdp                            float64
consumption_co2_per_gdp                float64
co2_per_unit_energy                    float64
coal_co2                               float64
cement_co2                             float64
flaring_co2                            float64
gas_co2                                float64
oil_co2                                float64
other_industry_co2                     float64
cement_co2_per_capita                  float64
coal_co2_per_capita                    float64
flaring_co2_per_capita                 float64
gas_co2_per_capita                     float64
oil_co2_per_capita                     float64
other_co2_per_capita                   float64
trade_co2_share                        float64
share_global_cement_co2                float64
share_global_coal_co2                  float64
share_global_flaring_co2               float64
share_global_gas_co2                   float64
share_global_oil_co2                   float64
share_global_other_co2                 float64
cumulative_cement_co2                  float64
cumulative_coal_co2                    float64
cumulative_flaring_co2                 float64
cumulative_gas_co2                     float64
cumulative_oil_co2                     float64
cumulative_other_co2                   float64
share_global_cumulative_cement_co2     float64
share_global_cumulative_coal_co2       float64
share_global_cumulative_flaring_co2    float64
share_global_cumulative_gas_co2        float64
share_global_cumulative_oil_co2        float64
share_global_cumulative_other_co2      float64
total_ghg                              float64
ghg_per_capita                         float64
methane                                float64
methane_per_capita                     float64
nitrous_oxide                          float64
nitrous_oxide_per_capita               float64
population                             float64
gdp                                    float64
primary_energy_consumption             float64
energy_per_capita                      float64
energy_per_gdp                         float64
dtype: object

In [11]:
# remove NaNs

carbon2_df = carbon_df.dropna()

In [12]:
carbon2_df

,iso_code,country,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
1565,AUS,Australia,1990,279.365,245.907,0.67,1.864,-33.458,16.471,14.499,...,30.140,162.19,9.563,82.27,4.851,1.696060e+07,4.641366e+11,1057.157,62328.710,2.244
1566,AUS,Australia,1991,281.872,247.517,0.90,2.507,-34.355,16.398,14.400,...,29.733,161.90,9.419,81.35,4.733,1.718924e+07,4.610038e+11,1050.408,61109.317,2.293
1567,AUS,Australia,1992,286.332,249.781,1.58,4.461,-36.551,16.454,14.353,...,29.498,161.32,9.270,80.52,4.627,1.740218e+07,4.778432e+11,1061.060,60973.443,2.183
1568,AUS,Australia,1993,291.325,251.300,1.74,4.993,-40.025,16.550,14.276,...,29.143,157.97,8.974,80.33,4.563,1.760321e+07,5.008406e+11,1091.296,61994.866,2.191
1569,AUS,Australia,1994,300.084,262.619,3.01,8.760,-37.466,16.860,14.755,...,28.992,156.81,8.810,80.19,4.505,1.779853e+07,5.273462e+11,1134.833,63758.248,2.170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24063,USA,United States,2016,5248.024,5576.720,-2.30,-123.747,328.696,16.247,17.264,...,18.059,629.38,1.948,251.70,0.779,3.230160e+08,1.716256e+13,25560.520,79130.818,1.486
24913,OWID_WRL,World,1990,22749.574,22749.574,1.53,342.742,0.000,4.270,4.270,...,6.564,7415.58,1.392,2460.54,0.462,5.327529e+09,4.301825e+13,95062.948,17844.721,2.201
24923,OWID_WRL,World,2000,25234.207,25234.207,2.92,715.245,0.000,4.107,4.107,...,6.091,7173.99,1.168,2554.89,0.416,6.143777e+09,5.986666e+13,109583.378,17837.305,1.912
24933,OWID_WRL,World,2010,33343.300,33343.300,5.49,1736.258,-0.000,4.793,4.793,...,6.692,8170.01,1.174,2860.55,0.411,6.957138e+09,8.980730e+13,140562.373,20204.963,1.588
24939,OWID_WRL,World,2016,35452.459,35452.459,-0.12,-43.947,-0.000,4.750,4.750,...,6.613,8550.06,1.146,3054.00,0.409,7.464344e+09,1.071343e+14,152944.938,20490.955,1.429

In [16]:
# dropping columns not needed
carbon_focus_df = carbon2_df.drop(columns=['ghg_per_capita', 'methane', 'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita', 'population', 'gdp', 'primary_energy_consumption', 'energy_per_capita', 
                                           'energy_per_gdp', 'total_ghg'])

In [17]:
carbon_focus_df.head(20)

,iso_code,country,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,...,cumulative_flaring_co2,cumulative_gas_co2,cumulative_oil_co2,cumulative_other_co2,share_global_cumulative_cement_co2,share_global_cumulative_coal_co2,share_global_cumulative_flaring_co2,share_global_cumulative_gas_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2
1565,AUS,Australia,1990,279.365,245.907,0.67,1.864,-33.458,16.471,14.499,...,9.829,374.449,2243.966,2.252,0.74,1.10,0.12,0.48,0.83,0.12
1566,AUS,Australia,1991,281.872,247.517,0.90,2.507,-34.355,16.398,14.400,...,16.889,407.510,2332.952,4.500,0.74,1.11,0.20,0.50,0.84,0.22
1567,AUS,Australia,1992,286.332,249.781,1.58,4.461,-36.551,16.454,14.353,...,24.239,441.697,2421.427,6.875,0.73,1.13,0.28,0.51,0.84,0.30
1568,AUS,Australia,1993,291.325,251.300,1.74,4.993,-40.025,16.550,14.276,...,31.436,477.669,2512.582,9.470,0.72,1.14,0.35,0.53,0.84,0.38
1569,AUS,Australia,1994,300.084,262.619,3.01,8.760,-37.466,16.860,14.755,...,38.466,515.507,2606.505,12.535,0.72,1.15,0.42,0.55,0.85,0.46
1570,AUS,Australia,1995,308.023,265.935,2.65,7.938,-42.087,17.119,14.780,...,45.597,555.732,2703.583,15.472,0.71,1.16,0.49,0.56,0.86,0.53
1571,AUS,Australia,1996,316.332,273.242,2.70,8.310,-43.090,17.391,15.022,...,52.455,596.064,2803.686,18.560,0.70,1.17,0.55,0.58,0.86,0.59
1572,AUS,Australia,1997,327.110,282.701,3.41,10.777,-44.409,17.790,15.375,...,59.285,638.014,2904.171,21.908,0.70,1.19,0.60,0.59,0.87,0.65
1573,AUS,Australia,1998,338.697,300.016,3.54,11.588,-38.681,18.222,16.141,...,66.281,682.105,3004.689,25.423,0.69,1.20,0.66,0.61,0.87,0.71
1574,AUS,Australia,1999,346.599,298.021,2.33,7.902,-48.578,18.448,15.862,...,73.511,728.066,3105.997,29.096,0.68,1.22,0.71,0.62,0.87,0.76
1575,AUS,Australia,2000,351.820,291.343,1.51,5.221,-60.477,18.525,15.341,...,81.514,774.951,3208.973,32.466,0.68,1.23,0.77,0.64,0.88,0.81
1576,AUS,Australia,2001,360.455,298.181,2.45,8.635,-62.273,18.779,15.535,...,89.762,824.720,3312.510,35.958,0.67,1.25,0.83,0.65,0.88,0.85
1577,AUS,Australia,2002,367.113,320.756,1.85,6.658,-46.357,18.922,16.533,...,97.893,876.073,3418.636,39.842,0.66,1.26,0.88,0.67,0.88,0.89
1578,AUS,Australia,2003,373.233,334.250,1.67,6.120,-38.983,19.019,17.033,...,105.129,926.306,3529.379,43.779,0.65,1.27,0.92,0.68,0.89,0.94
1579,AUS,Australia,2004,386.766,347.394,3.63,13.533,-39.372,19.455,17.475,...,112.059,979.365,3644.317,47.733,0.64,1.28,0.95,0.69,0.89,0.97
1580,AUS,Australia,2005,387.602,342.612,0.22,0.835,-44.990,19.209,16.979,...,119.002,1034.046,3761.261,51.639,0.63,1.29,0.99,0.70,0.90,1.00
1581,AUS,Australia,2006,397.295,361.562,2.50,9.693,-35.733,19.355,17.615,...,126.139,1090.555,3880.129,55.541,0.62,1.30,1.02,0.72,0.90,1.03
1582,AUS,Australia,2007,401.926,372.622,1.17,4.631,-29.303,19.216,17.815,...,133.688,1151.955,4000.290,59.648,0.60,1.31,1.05,0.73,0.91,1.05
1583,AUS,Australia,2008,409.653,367.687,1.92,7.728,-41.966,19.203,17.236,...,141.271,1214.570,4124.258,63.804,0.59,1.31,1.08,0.74,0.91,1.08
1584,AUS,Australia,2009,401.321,384.061,-2.03,-8.332,-17.260,18.451,17.657,...,149.125,1276.792,4244.901,67.489,0.58,1.32,1.11,0.75,0.92,1.10

In [18]:
# Saving cleaned data
file_path = "carbon_data_cleaned.csv"
carbon_focus_df.to_csv(file_path, index=False)