In [1]:
# import dependencies
import pandas as pd
import os

In [3]:
# read csv file into dataframe
df = pd.read_csv('co2 data by country by year.txt')
df.head(20)

,iso_code,country,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,NaN,NaN,NaN,NaN,0.002,NaN,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,NaN,475.00,0.070,NaN,0.011,NaN,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,NaN,8.70,0.007,NaN,0.012,NaN,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,NaN,0.00,0.000,NaN,0.012,NaN,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001732e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,NaN,16.00,0.015,NaN,0.013,NaN,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
5,AFG,Afghanistan,1954,0.106,NaN,0.00,0.000,NaN,0.013,NaN,...,NaN,NaN,NaN,NaN,NaN,8151316.0,1.086636e+10,NaN,NaN,NaN
6,AFG,Afghanistan,1955,0.154,NaN,44.83,0.048,NaN,0.019,NaN,...,NaN,NaN,NaN,NaN,NaN,8270992.0,1.107819e+10,NaN,NaN,NaN
7,AFG,Afghanistan,1956,0.183,NaN,19.05,0.029,NaN,0.022,NaN,...,NaN,NaN,NaN,NaN,NaN,8398873.0,1.158124e+10,NaN,NaN,NaN
8,AFG,Afghanistan,1957,0.293,NaN,60.00,0.110,NaN,0.034,NaN,...,NaN,NaN,NaN,NaN,NaN,8535157.0,1.157897e+10,NaN,NaN,NaN
9,AFG,Afghanistan,1958,0.330,NaN,12.50,0.037,NaN,0.038,NaN,...,NaN,NaN,NaN,NaN,NaN,8680097.0,1.223884e+10,NaN,NaN,NaN
10,AFG,Afghanistan,1959,0.385,NaN,16.62,0.055,NaN,0.044,NaN,...,NaN,NaN,NaN,NaN,NaN,8833947.0,1.257988e+10,NaN,NaN,NaN
11,AFG,Afghanistan,1960,0.414,NaN,7.62,0.029,NaN,0.046,NaN,...,NaN,NaN,NaN,NaN,NaN,8996967.0,1.303325e+10,NaN,NaN,NaN
12,AFG,Afghanistan,1961,0.491,NaN,18.58,0.077,NaN,0.054,NaN,...,NaN,NaN,NaN,NaN,NaN,9169406.0,1.314629e+10,NaN,NaN,NaN
13,AFG,Afghanistan,1962,0.689,NaN,40.30,0.198,NaN,0.074,NaN,...,NaN,NaN,NaN,NaN,NaN,9351442.0,1.336763e+10,NaN,NaN,NaN
14,AFG,Afghanistan,1963,0.707,NaN,2.63,0.018,NaN,0.074,NaN,...,NaN,NaN,NaN,NaN,NaN,9543200.0,1.363030e+10,NaN,NaN,NaN
15,AFG,Afghanistan,1964,0.839,NaN,18.65,0.132,NaN,0.086,NaN,...,NaN,NaN,NaN,NaN,NaN,9744772.0,1.387050e+10,NaN,NaN,NaN
16,AFG,Afghanistan,1965,1.007,NaN,20.08,0.168,NaN,0.101,NaN,...,NaN,NaN,NaN,NaN,NaN,9956318.0,1.418742e+10,NaN,NaN,NaN
17,AFG,Afghanistan,1966,1.091,NaN,8.37,0.084,NaN,0.107,NaN,...,NaN,NaN,NaN,NaN,NaN,10174840.0,1.432526e+10,NaN,NaN,NaN
18,AFG,Afghanistan,1967,1.282,NaN,17.48,0.191,NaN,0.123,NaN,...,NaN,NaN,NaN,NaN,NaN,10399936.0,1.473403e+10,NaN,NaN,NaN
19,AFG,Afghanistan,1968,1.223,NaN,-4.56,-0.058,NaN,0.115,NaN,...,NaN,NaN,NaN,NaN,NaN,10637064.0,1.525425e+10,NaN,NaN,NaN

In [22]:
# group all data by year and add up values
df2 = df.groupby('year', as_index=False).sum()
df2.head(20)

,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,share_global_co2,cumulative_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,1750,46.755,0.0,0.00,0.000,0.0,4.040,0.0,500.0,46.755,...,0.0,0.0,0.0,0.0,0.0,905258593.0,0.0,0.0,0.0,0.0
1,1751,46.755,0.0,0.00,0.000,0.0,0.000,0.0,500.0,93.505,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1752,46.770,0.0,0.20,0.020,0.0,0.000,0.0,500.0,140.275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1753,46.770,0.0,0.00,0.000,0.0,0.000,0.0,500.0,187.045,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1754,46.790,0.0,0.20,0.020,0.0,0.000,0.0,500.0,233.835,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1755,46.810,0.0,0.20,0.020,0.0,0.000,0.0,500.0,280.645,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1756,50.030,0.0,34.45,3.225,0.0,0.000,0.0,500.0,330.675,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1757,50.050,0.0,0.20,0.020,0.0,0.000,0.0,500.0,380.725,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1758,50.070,0.0,0.20,0.020,0.0,0.000,0.0,500.0,430.795,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1759,50.085,0.0,0.20,0.020,0.0,0.000,0.0,500.0,480.880,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,1760,50.085,0.0,0.00,0.000,0.0,4.093,0.0,500.0,530.970,...,0.0,0.0,0.0,0.0,0.0,946917311.0,0.0,0.0,0.0,0.0
11,1761,54.870,0.0,47.75,4.780,0.0,0.000,0.0,500.0,585.835,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1762,54.885,0.0,0.15,0.020,0.0,0.000,0.0,500.0,640.725,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,1763,54.905,0.0,0.15,0.020,0.0,0.000,0.0,500.0,695.630,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,1764,54.925,0.0,0.15,0.020,0.0,0.000,0.0,500.0,750.550,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,1765,54.940,0.0,0.15,0.020,0.0,0.000,0.0,500.0,805.495,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,1766,61.300,0.0,57.85,6.355,0.0,0.000,0.0,500.0,866.790,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1767,61.315,0.0,0.15,0.020,0.0,0.000,0.0,500.0,928.110,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,1768,61.335,0.0,0.15,0.020,0.0,0.000,0.0,500.0,989.445,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,1769,61.355,0.0,0.15,0.020,0.0,0.000,0.0,500.0,1050.800,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
df2.tail(20)

,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,share_global_co2,cumulative_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
251,2001,93999.371,91886.441,1099.21,1001.337,-561.690,1188.594,807.183,369.27,4187298.751,...,1543.130,14944.74,380.185,5428.03,116.833,1.866642e+10,6.183268e+13,280141.617,5092960.096,317.778
252,2002,95821.331,93911.556,841.52,1821.792,-327.430,1195.931,817.900,367.93,4283120.080,...,1624.690,15505.92,398.846,5558.41,116.920,1.890473e+10,6.395367e+13,285480.038,5189456.594,307.778
253,2003,100340.414,98413.548,1193.64,4519.083,-315.318,1226.914,875.742,366.60,4383460.486,...,1655.394,15574.77,405.783,5590.65,115.256,1.914294e+10,6.658458e+13,294247.498,5266017.189,303.465
254,2004,104330.579,102482.594,1283.93,3990.167,-118.050,1244.552,877.372,364.42,4487791.071,...,1582.994,15905.02,387.312,5721.69,113.224,1.938284e+10,7.032784e+13,306876.055,5394015.694,293.374
255,2005,107354.795,105683.247,592.78,3024.204,115.835,1245.040,899.828,362.62,4595145.867,...,1633.532,15862.42,394.312,5711.68,113.791,1.962506e+10,7.398377e+13,315477.690,5488770.842,275.513
256,2006,110616.399,109164.020,794.34,3261.621,386.477,1258.943,930.762,361.64,4705762.268,...,1558.991,16206.97,381.299,5770.06,111.766,1.986988e+10,7.822873e+13,322787.288,5557152.081,262.926
257,2007,113346.855,112012.836,1067.97,2730.454,534.365,1275.363,918.632,359.94,4819109.109,...,1574.174,16237.04,383.269,5867.58,112.677,2.011716e+10,8.253127e+13,331239.004,5601194.435,247.427
258,2008,115021.013,113551.059,590.22,1666.785,469.801,1261.985,955.939,358.66,4934129.980,...,1537.699,16370.36,370.616,5816.43,110.499,2.036658e+10,8.501959e+13,333908.966,5626631.596,236.632
259,2009,112661.081,110713.211,149.15,-2359.931,-71.141,1205.466,891.764,356.48,5046791.047,...,1463.960,16493.85,359.606,5797.39,104.501,2.061761e+10,8.508831e+13,326803.645,5371971.834,237.801
260,2010,118593.920,116740.403,1288.99,5932.837,112.790,1210.391,905.462,355.62,5165384.968,...,1505.895,16656.60,366.598,5910.03,108.829,2.086978e+10,1.799435e+14,341751.057,5572348.534,234.946
261,2011,122025.592,120289.790,902.54,3431.674,282.838,1209.633,866.623,353.97,5287410.553,...,1445.392,16856.78,361.265,6066.97,112.494,2.112288e+10,9.391711e+13,348091.982,5474134.418,223.303
262,2012,123738.518,121761.053,544.27,1712.937,47.653,1211.513,904.780,353.71,5411149.076,...,1430.284,17055.36,351.999,6121.20,108.005,2.137678e+10,9.661666e+13,351233.434,5499730.429,220.560
263,2013,124342.031,122339.246,378.24,603.515,27.099,1184.825,891.883,352.39,5535491.103,...,1446.300,17003.17,352.760,6065.74,105.178,2.163103e+10,9.962531e+13,357407.510,5501939.932,217.661
264,2014,124746.837,122635.458,849.49,404.812,-33.014,1185.569,878.858,350.98,5660237.941,...,1405.715,17295.46,342.986,6185.17,103.454,2.188515e+10,1.028445e+14,359364.730,5466506.744,213.780
265,2015,124780.495,122300.376,516.96,33.670,-364.772,1175.392,873.651,351.50,5785018.449,...,1480.963,17650.22,362.513,6291.99,107.669,2.213865e+10,1.056939e+14,361480.299,5528647.374,212.027
266,2016,124705.642,121980.559,639.81,-74.853,-557.147,1156.831,861.637,351.67,5909724.088,...,1415.378,17424.08,345.519,6291.93,105.005,2.239131e+10,2.147076e+14,366170.181,5562418.068,208.589
267,2017,126304.716,123574.569,543.59,1599.069,-497.205,1156.251,865.483,351.48,6036028.791,...,0.000,0.00,0.000,0.00,0.000,2.264281e+10,2.211738e+14,366923.317,3678183.705,0.000
268,2018,128452.538,125752.918,441.14,2147.827,-424.568,1152.783,866.311,350.47,6164481.333,...,0.000,0.00,0.000,0.00,0.000,2.289184e+10,2.276454e+14,376507.961,3698476.648,0.000
269,2019,128422.887,125634.241,504.75,-29.640,-466.739,1165.000,859.131,349.84,6292904.222,...,0.000,0.00,0.000,0.00,0.000,2.313895e+10,0.000000e+00,380148.487,3659567.475,0.000
270,2020,121592.746,34807.259,-1637.56,-6830.141,0.000,1076.428,4.465,349.29,6414496.975,...,0.000,0.00,0.000,0.00,0.000,2.338292e+10,0.000000e+00,0.000,0.000,0.000

In [28]:
# drop all data older than 1950
df3 = df2.drop(df2[df2.year < 1950].index)
df3.head(20)

,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,share_global_co2,cumulative_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
200,1950,23193.336,0.000,81429.51,2292.727,0.0,943.286,0.000,386.30,935424.702,...,0.0,0.0,0.0,0.0,0.0,7.570713e+09,1.585967e+13,0.000,0.000,0.000
201,1951,24765.194,0.000,2185.53,1577.008,0.0,1214.978,0.000,388.14,960063.734,...,0.0,0.0,0.0,0.0,0.0,7.712655e+09,7.992201e+12,0.000,0.000,0.000
202,1952,25203.424,0.000,2428.02,438.318,0.0,834.737,0.000,389.69,985256.050,...,0.0,0.0,0.0,0.0,0.0,7.852545e+09,8.401431e+12,0.000,0.000,0.000
203,1953,25929.893,0.000,1321.57,725.984,0.0,880.578,0.000,390.01,1011312.109,...,0.0,0.0,0.0,0.0,0.0,7.992062e+09,8.884521e+12,0.000,0.000,0.000
204,1954,26744.552,0.000,9797.03,813.240,0.0,1378.627,0.000,393.87,1038067.764,...,0.0,0.0,0.0,0.0,0.0,8.133217e+09,9.099744e+12,0.000,0.000,0.000
205,1955,29264.525,0.000,4165.42,2519.797,0.0,1214.075,0.000,393.12,1067332.296,...,0.0,0.0,0.0,0.0,0.0,8.283968e+09,9.694332e+12,0.000,0.000,0.000
206,1956,31190.093,0.000,1797.83,1925.567,0.0,1417.809,0.000,393.52,1098522.384,...,0.0,0.0,0.0,0.0,0.0,8.431613e+09,1.009736e+13,0.000,0.000,0.000
207,1957,32296.584,0.000,1763.42,1106.494,0.0,1096.454,0.000,394.52,1130818.787,...,0.0,0.0,0.0,0.0,0.0,8.583604e+09,1.047714e+13,0.000,0.000,0.000
208,1958,33117.274,0.000,1269.44,820.912,0.0,996.436,0.000,393.34,1163926.282,...,0.0,0.0,0.0,0.0,0.0,8.760051e+09,1.071646e+13,0.000,0.000,0.000
209,1959,34633.663,8856.189,2058.72,1516.355,0.0,1119.316,2.972,390.89,1198557.287,...,0.0,0.0,0.0,0.0,0.0,8.933658e+09,1.127617e+13,0.000,0.000,0.000
210,1960,36787.272,9386.934,4040.17,2153.617,0.0,1027.878,3.093,391.86,1235344.553,...,0.0,0.0,0.0,0.0,0.0,9.100095e+09,2.571552e+13,0.000,0.000,0.000
211,1961,37222.970,9417.463,2149.22,435.686,0.0,1046.395,3.046,395.11,1272567.524,...,0.0,0.0,0.0,0.0,0.0,9.270281e+09,1.290320e+13,0.000,0.000,0.000
212,1962,38731.697,9750.057,1962.49,1508.672,0.0,1082.957,3.095,397.17,1311299.139,...,0.0,0.0,0.0,0.0,0.0,9.445975e+09,1.360457e+13,0.000,0.000,0.000
213,1963,40905.925,10271.524,4710.07,2174.236,0.0,1138.645,3.199,398.26,1352205.064,...,0.0,0.0,0.0,0.0,0.0,9.627633e+09,1.432947e+13,0.000,0.000,0.000
214,1964,43134.197,10828.858,3064.93,2228.219,0.0,1150.748,3.308,398.32,1395339.333,...,0.0,0.0,0.0,0.0,0.0,9.817057e+09,1.530738e+13,0.000,0.000,0.000
215,1965,44979.444,11317.233,2417.32,1845.255,0.0,1108.269,3.389,397.37,1440318.776,...,0.0,0.0,0.0,0.0,0.0,1.001378e+10,1.611487e+13,107916.330,1588233.418,137.282
216,1966,47046.992,11865.861,2163.88,2067.543,0.0,1069.414,3.482,396.33,1487365.770,...,0.0,0.0,0.0,0.0,0.0,1.021871e+10,1.697124e+13,113424.747,1624895.105,137.667
217,1967,48536.547,12243.046,6973.37,1489.559,0.0,1135.557,3.519,396.35,1535902.316,...,0.0,0.0,0.0,0.0,0.0,1.043118e+10,1.763954e+13,117427.523,1682770.594,136.808
218,1968,51174.894,12909.913,2947.39,2638.345,0.0,1131.225,3.635,396.33,1587077.201,...,0.0,0.0,0.0,0.0,0.0,1.064960e+10,1.860884e+13,124855.911,1819120.107,138.815
219,1969,54504.030,13766.571,4137.46,3329.136,0.0,1328.266,3.797,395.82,1641581.231,...,0.0,0.0,0.0,0.0,0.0,1.087178e+10,1.970948e+13,133292.981,1909769.181,136.931

In [31]:
df3.columns

Index(['year', 'co2', 'consumption_co2', 'co2_growth_prct', 'co2_growth_abs',
       'trade_co2', 'co2_per_capita', 'consumption_co2_per_capita',
       'share_global_co2', 'cumulative_co2', 'share_global_cumulative_co2',
       'co2_per_gdp', 'consumption_co2_per_gdp', 'co2_per_unit_energy',
       'coal_co2', 'cement_co2', 'flaring_co2', 'gas_co2', 'oil_co2',
       'other_industry_co2', 'cement_co2_per_capita', 'coal_co2_per_capita',
       'flaring_co2_per_capita', 'gas_co2_per_capita', 'oil_co2_per_capita',
       'other_co2_per_capita', 'trade_co2_share', 'share_global_cement_co2',
       'share_global_coal_co2', 'share_global_flaring_co2',
       'share_global_gas_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'cumulative_cement_co2',
       'cumulative_coal_co2', 'cumulative_flaring_co2', 'cumulative_gas_co2',
       'cumulative_oil_co2', 'cumulative_other_co2',
       'share_global_cumulative_cement_co2',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_oil_co2',
       'share_global_cumulative_other_co2', 'total_ghg', 'ghg_per_capita',
       'methane', 'methane_per_capita', 'nitrous_oxide',
       'nitrous_oxide_per_capita', 'population', 'gdp',
       'primary_energy_consumption', 'energy_per_capita', 'energy_per_gdp'],
      dtype='object')

In [32]:
# drop unused columns 
df4 = df3.drop(['consumption_co2',
    'co2_growth_prct',
    'co2_growth_abs',
    'trade_co2',
    'consumption_co2_per_capita',
    'share_global_co2',
    'cumulative_co2',
    'share_global_cumulative_co2',
    'co2_per_gdp',
    'consumption_co2_per_gdp',
    'cement_co2_per_capita',
    'coal_co2_per_capita',
    'flaring_co2_per_capita',
    'gas_co2_per_capita',
    'oil_co2_per_capita',
    'other_co2_per_capita',
    'trade_co2_share',
    'share_global_cement_co2',
    'share_global_coal_co2',
    'share_global_flaring_co2',
    'share_global_gas_co2',
    'share_global_oil_co2',
    'share_global_other_co2',
    'cumulative_cement_co2',
    'cumulative_coal_co2',
    'cumulative_flaring_co2',
    'cumulative_gas_co2',
    'cumulative_oil_co2',
    'cumulative_other_co2',
    'share_global_cumulative_cement_co2',
    'share_global_cumulative_coal_co2',
    'share_global_cumulative_flaring_co2',
    'share_global_cumulative_gas_co2',
    'share_global_cumulative_oil_co2',
    'share_global_cumulative_other_co2'], axis=1)
df4.head(20)

,year,co2,co2_per_capita,co2_per_unit_energy,coal_co2,cement_co2,flaring_co2,gas_co2,oil_co2,other_industry_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
200,1950,23193.336,943.286,0.000,15959.768,272.887,223.550,1110.931,5611.231,9.976,...,0.0,0.0,0.0,0.0,0.0,7.570713e+09,1.585967e+13,0.000,0.000,0.000
201,1951,24765.194,1214.978,0.000,16981.583,309.265,243.305,1306.674,5907.881,11.002,...,0.0,0.0,0.0,0.0,0.0,7.712655e+09,7.992201e+12,0.000,0.000,0.000
202,1952,25203.424,834.737,0.000,16927.201,331.430,259.877,1405.429,6263.420,10.710,...,0.0,0.0,0.0,0.0,0.0,7.852545e+09,8.401431e+12,0.000,0.000,0.000
203,1953,25929.893,880.578,0.000,17104.163,368.454,248.979,1498.933,6689.993,12.910,...,0.0,0.0,0.0,0.0,0.0,7.992062e+09,8.884521e+12,0.000,0.000,0.000
204,1954,26744.552,1378.627,0.000,17319.801,400.182,236.584,1588.220,7182.609,11.442,...,0.0,0.0,0.0,0.0,0.0,8.133217e+09,9.099744e+12,0.000,0.000,0.000
205,1955,29264.525,1214.075,0.000,18677.318,444.211,309.049,1741.540,8071.511,13.936,...,0.0,0.0,0.0,0.0,0.0,8.283968e+09,9.694332e+12,0.000,0.000,0.000
206,1956,31190.093,1417.809,0.000,19630.649,480.046,345.132,1883.051,8830.105,14.084,...,0.0,0.0,0.0,0.0,0.0,8.431613e+09,1.009736e+13,0.000,0.000,0.000
207,1957,32296.584,1096.454,0.000,20032.870,507.553,338.071,2100.913,9296.722,13.644,...,0.0,0.0,0.0,0.0,0.0,8.583604e+09,1.047714e+13,0.000,0.000,0.000
208,1958,33117.274,996.436,0.000,20128.845,537.115,306.731,2326.435,9799.654,12.322,...,0.0,0.0,0.0,0.0,0.0,8.760051e+09,1.071646e+13,0.000,0.000,0.000
209,1959,34633.663,1119.316,0.000,20659.402,603.103,298.275,2531.718,10516.306,16.578,...,0.0,0.0,0.0,0.0,0.0,8.933658e+09,1.127617e+13,0.000,0.000,0.000
210,1960,36787.272,1027.878,0.000,21511.480,657.864,291.993,2820.774,11422.647,55.014,...,0.0,0.0,0.0,0.0,0.0,9.100095e+09,2.571552e+13,0.000,0.000,0.000
211,1961,37222.970,1046.395,0.000,20937.959,696.050,284.198,3029.746,12187.367,58.438,...,0.0,0.0,0.0,0.0,0.0,9.270281e+09,1.290320e+13,0.000,0.000,0.000
212,1962,38731.697,1082.957,0.000,20991.352,749.709,283.107,3362.055,13254.638,60.554,...,0.0,0.0,0.0,0.0,0.0,9.445975e+09,1.360457e+13,0.000,0.000,0.000
213,1963,40905.925,1138.645,0.000,21739.527,789.438,306.503,3667.333,14307.870,63.502,...,0.0,0.0,0.0,0.0,0.0,9.627633e+09,1.432947e+13,0.000,0.000,0.000
214,1964,43134.197,1150.748,0.000,22115.607,876.755,395.816,4087.927,15553.140,69.960,...,0.0,0.0,0.0,0.0,0.0,9.817057e+09,1.530738e+13,0.000,0.000,0.000
215,1965,44979.444,1108.269,29.638,22292.833,919.388,462.239,4410.887,16790.497,69.064,...,0.0,0.0,0.0,0.0,0.0,1.001378e+10,1.611487e+13,107916.330,1588233.418,137.282
216,1966,47046.992,1069.414,29.661,22407.513,989.699,514.579,4820.632,18205.910,72.442,...,0.0,0.0,0.0,0.0,0.0,1.021871e+10,1.697124e+13,113424.747,1624895.105,137.667
217,1967,48536.547,1135.557,28.111,22049.196,1025.830,671.973,5192.465,19485.488,74.400,...,0.0,0.0,0.0,0.0,0.0,1.043118e+10,1.763954e+13,117427.523,1682770.594,136.808
218,1968,51174.894,1131.225,25.830,22274.489,1091.649,715.043,5693.334,21284.593,77.186,...,0.0,0.0,0.0,0.0,0.0,1.064960e+10,1.860884e+13,124855.911,1819120.107,138.815
219,1969,54504.030,1328.266,28.353,23015.217,1154.300,865.719,6254.566,23089.103,83.416,...,0.0,0.0,0.0,0.0,0.0,1.087178e+10,1.970948e+13,133292.981,1909769.181,136.931

In [35]:
df4.dtypes

year                            int64
co2                           float64
co2_per_capita                float64
co2_per_unit_energy           float64
coal_co2                      float64
cement_co2                    float64
flaring_co2                   float64
gas_co2                       float64
oil_co2                       float64
other_industry_co2            float64
total_ghg                     float64
ghg_per_capita                float64
methane                       float64
methane_per_capita            float64
nitrous_oxide                 float64
nitrous_oxide_per_capita      float64
population                    float64
gdp                           float64
primary_energy_consumption    float64
energy_per_capita             float64
energy_per_gdp                float64
dtype: object

In [34]:
# export dataframe to csv file
df4.to_csv(('co2_byYear.csv'), index=False)