In [1]:
import pandas as pd

In [2]:
carbon_df = pd.read_csv('owid-co2-data.csv')

In [3]:
carbon_df

,iso_code,country,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,NaN,NaN,NaN,NaN,0.002,NaN,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,NaN,475.00,0.070,NaN,0.011,NaN,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,NaN,8.70,0.007,NaN,0.012,NaN,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,NaN,0.00,0.000,NaN,0.012,NaN,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001732e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,NaN,16.00,0.015,NaN,0.013,NaN,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25199,ZWE,Zimbabwe,2016,10.738,12.153,-12.17,-1.488,1.415,0.765,0.866,...,4.703,11.92,0.85,6.55,0.467,14030338.0,2.096179e+10,47.5,3385.574,1.889
25200,ZWE,Zimbabwe,2017,9.582,11.248,-10.77,-1.156,1.666,0.673,0.790,...,NaN,NaN,NaN,NaN,NaN,14236599.0,2.194784e+10,NaN,NaN,NaN
25201,ZWE,Zimbabwe,2018,11.854,13.163,23.72,2.273,1.308,0.821,0.912,...,NaN,NaN,NaN,NaN,NaN,14438812.0,2.271535e+10,NaN,NaN,NaN
25202,ZWE,Zimbabwe,2019,10.949,12.422,-7.64,-0.905,1.473,0.748,0.848,...,NaN,NaN,NaN,NaN,NaN,14645473.0,NaN,NaN,NaN,NaN
25203,ZWE,Zimbabwe,2020,10.531,NaN,-3.82,-0.418,NaN,0.709,NaN,...,NaN,NaN,NaN,NaN,NaN,14862927.0,NaN,NaN,NaN,NaN

In [13]:
# dropping columns not needed
carbon_focus_df = carbon_df.drop(columns=['consumption_co2', 'co2_growth_prct', 'co2_growth_abs', 'trade_co2', 'co2_per_capita', 'consumption_co2_per_capita',
                                          'share_global_co2', 'share_global_cumulative_co2', 'co2_per_gdp', 'consumption_co2_per_gdp', 'co2_per_unit_energy',
                                          'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_oil_co2', 'cumulative_other_co2', 'share_global_cumulative_cement_co2', 'share_global_cumulative_coal_co2',
                                          'share_global_cumulative_flaring_co2', 'share_global_cumulative_gas_co2', 'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
                                           'ghg_per_capita', 'methane', 'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita', 'population', 'gdp', 'primary_energy_consumption', 'energy_per_capita', 
                                           'energy_per_gdp', 'total_ghg', 'coal_co2', 'cement_co2', 'flaring_co2', 'gas_co2', 'oil_co2', 'other_co2_per_capita', 'trade_co2_share', 'share_global_cement_co2',
                                         'share_global_coal_co2', 'share_global_flaring_co2', 'share_global_gas_co2', 'share_global_oil_co2', 'share_global_other_co2', 'cumulative_cement_co2', 'cumulative_coal_co2',
                                         'other_industry_co2', 'cement_co2_per_capita', 'coal_co2_per_capita', 'flaring_co2_per_capita', 'gas_co2_per_capita', 'oil_co2_per_capita'])

In [14]:
carbon_focus_df.head(25)

   iso_code      country  year    co2  cumulative_co2
0       AFG  Afghanistan  1949  0.015           0.015
1       AFG  Afghanistan  1950  0.084           0.099
2       AFG  Afghanistan  1951  0.092           0.191
3       AFG  Afghanistan  1952  0.092           0.282
4       AFG  Afghanistan  1953  0.106           0.388
5       AFG  Afghanistan  1954  0.106           0.495
6       AFG  Afghanistan  1955  0.154           0.649
7       AFG  Afghanistan  1956  0.183           0.832
8       AFG  Afghanistan  1957  0.293           1.125
9       AFG  Afghanistan  1958  0.330           1.455
10      AFG  Afghanistan  1959  0.385           1.839
11      AFG  Afghanistan  1960  0.414           2.253
12      AFG  Afghanistan  1961  0.491           2.744
13      AFG  Afghanistan  1962  0.689           3.432
14      AFG  Afghanistan  1963  0.707           4.139
15      AFG  Afghanistan  1964  0.839           4.978
16      AFG  Afghanistan  1965  1.007           5.985
17      AFG  Afghanistan  1966  1.091           7.076
18      AFG  Afghanistan  1967  1.282           8.358
19      AFG  Afghanistan  1968  1.223           9.581
20      AFG  Afghanistan  1969  0.941          10.522
21      AFG  Afghanistan  1970  1.670          12.193
22      AFG  Afghanistan  1971  1.894          14.086
23      AFG  Afghanistan  1972  1.530          15.617
24      AFG  Afghanistan  1973  1.635          17.252

In [15]:
# Saving cleaned data
file_path = "pure_carbon_cleaned.csv"
carbon_focus_df.to_csv(file_path, index=False)