In [1]:
# import dependencies
import pandas as pd
import os

In [2]:
directory = "Severe Weather Event Data\details"
appended_data = []

# for loop to read in each CSV file in the directory into a dataframe,
# drop unnecessary columns, and append it to a dataframe

for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        full_filename = (os.path.join(directory, filename))
        df = pd.read_csv(full_filename, low_memory=False)
        df2 = df.drop(['BEGIN_YEARMONTH','BEGIN_DAY','BEGIN_TIME',
            'END_YEARMONTH','END_DAY','END_TIME','EPISODE_ID',
            'CZ_TYPE','CZ_FIPS','CZ_NAME','WFO','BEGIN_DATE_TIME',
            'CZ_TIMEZONE','END_DATE_TIME','SOURCE',
            'MAGNITUDE_TYPE','FLOOD_CAUSE','TOR_OTHER_WFO',
            'TOR_OTHER_CZ_STATE','TOR_OTHER_CZ_FIPS',
            'TOR_OTHER_CZ_NAME','BEGIN_RANGE','BEGIN_AZIMUTH',
            'BEGIN_LOCATION','END_RANGE','END_AZIMUTH',
            'END_LOCATION','END_LAT','END_LON',
            'EPISODE_NARRATIVE','EVENT_NARRATIVE',
            'DATA_SOURCE'], axis=1)
        # store DataFrame in list
        appended_data.append(df2)
        continue
    else:
        continue
appended_data = pd.concat(appended_data)
print(appended_data.shape)
appended_data.head(20)

(1702313, 19)

,EVENT_ID,STATE,STATE_FIPS,YEAR,MONTH_NAME,EVENT_TYPE,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,MAGNITUDE,CATEGORY,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,BEGIN_LAT,BEGIN_LON
0,10096222,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,250K,0,0.0,NaN,F3,3.4,400.0,35.12,-99.20
1,10120412,TEXAS,48.0,1950,April,Tornado,0,0,0,0,25K,0,0.0,NaN,F1,11.5,200.0,31.90,-98.60
2,10104927,PENNSYLVANIA,42.0,1950,July,Tornado,2,0,0,0,25K,0,0.0,NaN,F2,12.9,33.0,40.58,-75.70
3,10104928,PENNSYLVANIA,42.0,1950,July,Tornado,0,0,0,0,2.5K,0,0.0,NaN,F2,0.0,13.0,40.60,-76.75
4,10104929,PENNSYLVANIA,42.0,1950,July,Tornado,0,0,0,0,2.5K,0,0.0,NaN,F0,0.0,33.0,41.63,-79.68
5,10104930,PENNSYLVANIA,42.0,1950,August,Tornado,0,0,0,0,2.5K,0,0.0,NaN,F1,1.0,33.0,40.22,-75.00
6,10104931,PENNSYLVANIA,42.0,1950,November,Tornado,1,0,0,0,250K,0,0.0,NaN,F3,4.7,100.0,40.20,-76.12
7,10104932,PENNSYLVANIA,42.0,1950,November,Tornado,0,0,0,0,250K,0,0.0,NaN,F3,11.2,100.0,40.27,-76.07
8,10099490,OKLAHOMA,40.0,1950,September,Tornado,6,0,0,0,250K,0,0.0,NaN,F2,6.8,100.0,35.00,-96.25
9,10099491,OKLAHOMA,40.0,1950,September,Tornado,0,0,0,0,.25K,0,0.0,NaN,F0,0.0,33.0,34.83,-95.85
10,10099492,OKLAHOMA,40.0,1950,October,Tornado,0,0,0,0,25K,0,0.0,NaN,F1,15.8,33.0,36.73,-102.52
11,10073785,NEBRASKA,31.0,1950,June,Tornado,0,0,0,0,0K,0,0.0,NaN,F0,1.9,33.0,40.18,-98.03
12,10096216,OKLAHOMA,40.0,1950,February,Tornado,0,0,0,0,25K,0,0.0,NaN,F2,2.0,50.0,35.55,-97.60
13,10096217,OKLAHOMA,40.0,1950,March,Tornado,0,0,0,0,2.5K,0,0.0,NaN,F2,0.1,77.0,34.85,-95.75
14,10096218,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,25K,0,0.0,NaN,F2,1.0,100.0,35.82,-97.02
15,10096219,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,2.5K,0,0.0,NaN,F1,1.0,33.0,36.13,-95.83
16,10096220,OKLAHOMA,40.0,1950,April,Tornado,1,0,1,0,250K,0,0.0,NaN,F3,9.4,400.0,34.88,-99.28
17,10096221,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,250K,0,0.0,NaN,F3,8.0,400.0,35.00,-99.20
18,10096223,OKLAHOMA,40.0,1950,April,Tornado,32,0,5,0,250K,0,0.0,NaN,F4,4.5,200.0,35.08,-96.40
19,10096224,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,25K,0,0.0,NaN,F2,0.8,100.0,34.55,-96.20

In [3]:
# populate NULL values with 0
appended_data = appended_data.fillna(0)

print(appended_data.shape)
appended_data.head(20)

(1702313, 19)

,EVENT_ID,STATE,STATE_FIPS,YEAR,MONTH_NAME,EVENT_TYPE,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,MAGNITUDE,CATEGORY,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,BEGIN_LAT,BEGIN_LON
0,10096222,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,250K,0,0.0,0.0,F3,3.4,400.0,35.12,-99.20
1,10120412,TEXAS,48.0,1950,April,Tornado,0,0,0,0,25K,0,0.0,0.0,F1,11.5,200.0,31.90,-98.60
2,10104927,PENNSYLVANIA,42.0,1950,July,Tornado,2,0,0,0,25K,0,0.0,0.0,F2,12.9,33.0,40.58,-75.70
3,10104928,PENNSYLVANIA,42.0,1950,July,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F2,0.0,13.0,40.60,-76.75
4,10104929,PENNSYLVANIA,42.0,1950,July,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F0,0.0,33.0,41.63,-79.68
5,10104930,PENNSYLVANIA,42.0,1950,August,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F1,1.0,33.0,40.22,-75.00
6,10104931,PENNSYLVANIA,42.0,1950,November,Tornado,1,0,0,0,250K,0,0.0,0.0,F3,4.7,100.0,40.20,-76.12
7,10104932,PENNSYLVANIA,42.0,1950,November,Tornado,0,0,0,0,250K,0,0.0,0.0,F3,11.2,100.0,40.27,-76.07
8,10099490,OKLAHOMA,40.0,1950,September,Tornado,6,0,0,0,250K,0,0.0,0.0,F2,6.8,100.0,35.00,-96.25
9,10099491,OKLAHOMA,40.0,1950,September,Tornado,0,0,0,0,.25K,0,0.0,0.0,F0,0.0,33.0,34.83,-95.85
10,10099492,OKLAHOMA,40.0,1950,October,Tornado,0,0,0,0,25K,0,0.0,0.0,F1,15.8,33.0,36.73,-102.52
11,10073785,NEBRASKA,31.0,1950,June,Tornado,0,0,0,0,0K,0,0.0,0.0,F0,1.9,33.0,40.18,-98.03
12,10096216,OKLAHOMA,40.0,1950,February,Tornado,0,0,0,0,25K,0,0.0,0.0,F2,2.0,50.0,35.55,-97.60
13,10096217,OKLAHOMA,40.0,1950,March,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F2,0.1,77.0,34.85,-95.75
14,10096218,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,25K,0,0.0,0.0,F2,1.0,100.0,35.82,-97.02
15,10096219,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F1,1.0,33.0,36.13,-95.83
16,10096220,OKLAHOMA,40.0,1950,April,Tornado,1,0,1,0,250K,0,0.0,0.0,F3,9.4,400.0,34.88,-99.28
17,10096221,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,250K,0,0.0,0.0,F3,8.0,400.0,35.00,-99.20
18,10096223,OKLAHOMA,40.0,1950,April,Tornado,32,0,5,0,250K,0,0.0,0.0,F4,4.5,200.0,35.08,-96.40
19,10096224,OKLAHOMA,40.0,1950,April,Tornado,0,0,0,0,25K,0,0.0,0.0,F2,0.8,100.0,34.55,-96.20

In [4]:
# convert STATE_FIPS from FLOAT to INT
appended_data['STATE_FIPS'] = appended_data['STATE_FIPS'].astype(int)

print(appended_data.shape)
appended_data.head(20)

(1702313, 19)

,EVENT_ID,STATE,STATE_FIPS,YEAR,MONTH_NAME,EVENT_TYPE,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,MAGNITUDE,CATEGORY,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,BEGIN_LAT,BEGIN_LON
0,10096222,OKLAHOMA,40,1950,April,Tornado,0,0,0,0,250K,0,0.0,0.0,F3,3.4,400.0,35.12,-99.20
1,10120412,TEXAS,48,1950,April,Tornado,0,0,0,0,25K,0,0.0,0.0,F1,11.5,200.0,31.90,-98.60
2,10104927,PENNSYLVANIA,42,1950,July,Tornado,2,0,0,0,25K,0,0.0,0.0,F2,12.9,33.0,40.58,-75.70
3,10104928,PENNSYLVANIA,42,1950,July,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F2,0.0,13.0,40.60,-76.75
4,10104929,PENNSYLVANIA,42,1950,July,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F0,0.0,33.0,41.63,-79.68
5,10104930,PENNSYLVANIA,42,1950,August,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F1,1.0,33.0,40.22,-75.00
6,10104931,PENNSYLVANIA,42,1950,November,Tornado,1,0,0,0,250K,0,0.0,0.0,F3,4.7,100.0,40.20,-76.12
7,10104932,PENNSYLVANIA,42,1950,November,Tornado,0,0,0,0,250K,0,0.0,0.0,F3,11.2,100.0,40.27,-76.07
8,10099490,OKLAHOMA,40,1950,September,Tornado,6,0,0,0,250K,0,0.0,0.0,F2,6.8,100.0,35.00,-96.25
9,10099491,OKLAHOMA,40,1950,September,Tornado,0,0,0,0,.25K,0,0.0,0.0,F0,0.0,33.0,34.83,-95.85
10,10099492,OKLAHOMA,40,1950,October,Tornado,0,0,0,0,25K,0,0.0,0.0,F1,15.8,33.0,36.73,-102.52
11,10073785,NEBRASKA,31,1950,June,Tornado,0,0,0,0,0K,0,0.0,0.0,F0,1.9,33.0,40.18,-98.03
12,10096216,OKLAHOMA,40,1950,February,Tornado,0,0,0,0,25K,0,0.0,0.0,F2,2.0,50.0,35.55,-97.60
13,10096217,OKLAHOMA,40,1950,March,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F2,0.1,77.0,34.85,-95.75
14,10096218,OKLAHOMA,40,1950,April,Tornado,0,0,0,0,25K,0,0.0,0.0,F2,1.0,100.0,35.82,-97.02
15,10096219,OKLAHOMA,40,1950,April,Tornado,0,0,0,0,2.5K,0,0.0,0.0,F1,1.0,33.0,36.13,-95.83
16,10096220,OKLAHOMA,40,1950,April,Tornado,1,0,1,0,250K,0,0.0,0.0,F3,9.4,400.0,34.88,-99.28
17,10096221,OKLAHOMA,40,1950,April,Tornado,0,0,0,0,250K,0,0.0,0.0,F3,8.0,400.0,35.00,-99.20
18,10096223,OKLAHOMA,40,1950,April,Tornado,32,0,5,0,250K,0,0.0,0.0,F4,4.5,200.0,35.08,-96.40
19,10096224,OKLAHOMA,40,1950,April,Tornado,0,0,0,0,25K,0,0.0,0.0,F2,0.8,100.0,34.55,-96.20

In [6]:
# remove data after 2020 so that in lines up with CO2 data date range
appended_data = appended_data.drop(appended_data[appended_data.YEAR > 2020].index)

print(appended_data.shape)
appended_data.head(20)

(450455, 19)

,EVENT_ID,STATE,STATE_FIPS,YEAR,MONTH_NAME,EVENT_TYPE,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,MAGNITUDE,CATEGORY,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,BEGIN_LAT,BEGIN_LON
39216,5583648,MINNESOTA,27,1996,October,Hail,0,0,0,0,0,0,1.00,0.0,0,0.0,0.0,46.37,-94.20
39217,5582712,MINNESOTA,27,1996,October,Tornado,0,0,0,0,0,0,0.00,0.0,F0,0.5,25.0,47.00,-94.95
39218,5582713,MINNESOTA,27,1996,October,High Wind,0,0,0,0,2K,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39219,5582714,MINNESOTA,27,1996,October,High Wind,0,0,0,0,10K,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39220,5582715,MINNESOTA,27,1996,October,High Wind,0,0,0,0,10K,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39221,5583649,MINNESOTA,27,1996,October,Tornado,0,0,0,0,50K,0,0.00,0.0,F2,0.7,150.0,46.58,-93.88
39222,5583840,MAINE,23,1996,October,Storm Surge/Tide,0,0,0,0,.35M,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39223,5584372,MINNESOTA,27,1996,October,Thunderstorm Wind,0,0,0,0,0,0,60.00,0.0,0,0.0,0.0,45.23,-96.92
39224,5584373,MINNESOTA,27,1996,October,Hail,0,0,0,0,0,0,0.75,0.0,0,0.0,0.0,45.75,-93.17
39225,5572718,ARIZONA,4,1996,July,Flash Flood,0,0,0,0,0,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39226,5577442,MINNESOTA,27,1996,March,Blizzard,0,0,0,0,0,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39227,5725022,OKLAHOMA,40,1996,March,Thunderstorm Wind,0,0,0,0,0,0,0.52,0.0,0,0.0,0.0,0.00,0.00
39228,5577445,MINNESOTA,27,1996,March,Blizzard,0,0,0,0,0,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39229,5577446,MINNESOTA,27,1996,March,Blizzard,0,0,0,0,0,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39230,5725050,OKLAHOMA,40,1996,March,Thunderstorm Wind,0,0,0,0,0,0,0.52,0.0,0,0.0,0.0,0.00,0.00
39231,5577582,PENNSYLVANIA,42,1996,October,Flash Flood,0,0,0,0,0,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39232,5578331,CALIFORNIA,6,1996,October,Wildfire,3,0,0,0,4.5M,1M,0.00,0.0,0,0.0,0.0,0.00,0.00
39233,5577341,DELAWARE,10,1996,October,Flash Flood,0,0,0,0,0,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39234,5577342,MARYLAND,24,1996,October,Heavy Rain,0,0,0,0,0,0,0.00,0.0,0,0.0,0.0,0.00,0.00
39235,5567719,OHIO,39,1996,July,Flash Flood,0,0,0,0,0,0,0.00,0.0,0,0.0,0.0,0.00,0.00

In [7]:
# export data to CSV file
appended_data.to_csv(os.path.join(directory,'Results\SevereWeatherDetails_appended.csv'), index=False)