In [1]:
# import dependencies
import pandas as pd
import os

In [2]:
# read csv file into dataframe
df = pd.read_csv('co2 data by country by year.txt')
df.head(20)

,iso_code,country,year,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,NaN,NaN,NaN,NaN,0.002,NaN,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,NaN,475.00,0.070,NaN,0.011,NaN,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,NaN,8.70,0.007,NaN,0.012,NaN,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,NaN,0.00,0.000,NaN,0.012,NaN,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001732e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,NaN,16.00,0.015,NaN,0.013,NaN,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
5,AFG,Afghanistan,1954,0.106,NaN,0.00,0.000,NaN,0.013,NaN,...,NaN,NaN,NaN,NaN,NaN,8151316.0,1.086636e+10,NaN,NaN,NaN
6,AFG,Afghanistan,1955,0.154,NaN,44.83,0.048,NaN,0.019,NaN,...,NaN,NaN,NaN,NaN,NaN,8270992.0,1.107819e+10,NaN,NaN,NaN
7,AFG,Afghanistan,1956,0.183,NaN,19.05,0.029,NaN,0.022,NaN,...,NaN,NaN,NaN,NaN,NaN,8398873.0,1.158124e+10,NaN,NaN,NaN
8,AFG,Afghanistan,1957,0.293,NaN,60.00,0.110,NaN,0.034,NaN,...,NaN,NaN,NaN,NaN,NaN,8535157.0,1.157897e+10,NaN,NaN,NaN
9,AFG,Afghanistan,1958,0.330,NaN,12.50,0.037,NaN,0.038,NaN,...,NaN,NaN,NaN,NaN,NaN,8680097.0,1.223884e+10,NaN,NaN,NaN
10,AFG,Afghanistan,1959,0.385,NaN,16.62,0.055,NaN,0.044,NaN,...,NaN,NaN,NaN,NaN,NaN,8833947.0,1.257988e+10,NaN,NaN,NaN
11,AFG,Afghanistan,1960,0.414,NaN,7.62,0.029,NaN,0.046,NaN,...,NaN,NaN,NaN,NaN,NaN,8996967.0,1.303325e+10,NaN,NaN,NaN
12,AFG,Afghanistan,1961,0.491,NaN,18.58,0.077,NaN,0.054,NaN,...,NaN,NaN,NaN,NaN,NaN,9169406.0,1.314629e+10,NaN,NaN,NaN
13,AFG,Afghanistan,1962,0.689,NaN,40.30,0.198,NaN,0.074,NaN,...,NaN,NaN,NaN,NaN,NaN,9351442.0,1.336763e+10,NaN,NaN,NaN
14,AFG,Afghanistan,1963,0.707,NaN,2.63,0.018,NaN,0.074,NaN,...,NaN,NaN,NaN,NaN,NaN,9543200.0,1.363030e+10,NaN,NaN,NaN
15,AFG,Afghanistan,1964,0.839,NaN,18.65,0.132,NaN,0.086,NaN,...,NaN,NaN,NaN,NaN,NaN,9744772.0,1.387050e+10,NaN,NaN,NaN
16,AFG,Afghanistan,1965,1.007,NaN,20.08,0.168,NaN,0.101,NaN,...,NaN,NaN,NaN,NaN,NaN,9956318.0,1.418742e+10,NaN,NaN,NaN
17,AFG,Afghanistan,1966,1.091,NaN,8.37,0.084,NaN,0.107,NaN,...,NaN,NaN,NaN,NaN,NaN,10174840.0,1.432526e+10,NaN,NaN,NaN
18,AFG,Afghanistan,1967,1.282,NaN,17.48,0.191,NaN,0.123,NaN,...,NaN,NaN,NaN,NaN,NaN,10399936.0,1.473403e+10,NaN,NaN,NaN
19,AFG,Afghanistan,1968,1.223,NaN,-4.56,-0.058,NaN,0.115,NaN,...,NaN,NaN,NaN,NaN,NaN,10637064.0,1.525425e+10,NaN,NaN,NaN

In [5]:
# group all data by year and add up values
df2 = df.groupby(['year', 'country'], as_index=False).sum()
df2.head(20)

,year,country,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,share_global_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,1750,EU-28,9.351,0.0,0.00,0.000,0.0,1.007,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1750,Europe,9.351,0.0,0.00,0.000,0.0,1.007,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,150305974.0,0.0,0.0,0.0,0.0
2,1750,Europe (excl. EU-27),9.351,0.0,0.00,0.000,0.0,1.007,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1750,United Kingdom,9.351,0.0,0.00,0.000,0.0,1.007,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,9288174.0,0.0,0.0,0.0,0.0
4,1750,World,9.351,0.0,0.00,0.000,0.0,0.012,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,745664445.0,0.0,0.0,0.0,0.0
5,1751,EU-28,9.351,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1751,Europe,9.351,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1751,Europe (excl. EU-27),9.351,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1751,United Kingdom,9.351,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1751,World,9.351,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,1752,EU-28,9.354,0.0,0.04,0.004,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1752,Europe,9.354,0.0,0.04,0.004,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1752,Europe (excl. EU-27),9.354,0.0,0.04,0.004,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,1752,United Kingdom,9.354,0.0,0.04,0.004,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,1752,World,9.354,0.0,0.04,0.004,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,1753,EU-28,9.354,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,1753,Europe,9.354,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1753,Europe (excl. EU-27),9.354,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,1753,United Kingdom,9.354,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,1753,World,9.354,0.0,0.00,0.000,0.0,0.000,0.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df2.tail(20)

,year,country,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,share_global_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
25184,2020,Tunisia,28.127,0.000,-6.28,-1.884,0.0,2.380,0.000,0.08,...,0.0,0.0,0.0,0.0,0.0,1.181862e+07,0.0,0.0,0.0,0.0
25185,2020,Turkey,392.794,0.000,-1.64,-6.551,0.0,4.657,0.000,1.13,...,0.0,0.0,0.0,0.0,0.0,8.433907e+07,0.0,0.0,0.0,0.0
25186,2020,Turkmenistan,75.338,0.000,-1.29,-0.981,0.0,12.491,0.000,0.22,...,0.0,0.0,0.0,0.0,0.0,6.031187e+06,0.0,0.0,0.0,0.0
25187,2020,Turks and Caicos Islands,0.203,0.000,-11.51,-0.026,0.0,5.231,0.000,0.00,...,0.0,0.0,0.0,0.0,0.0,3.871800e+04,0.0,0.0,0.0,0.0
25188,2020,Tuvalu,0.008,0.000,0.15,0.000,0.0,0.642,0.000,0.00,...,0.0,0.0,0.0,0.0,0.0,1.179200e+04,0.0,0.0,0.0,0.0
25189,2020,Uganda,4.892,0.000,-14.48,-0.829,0.0,0.107,0.000,0.01,...,0.0,0.0,0.0,0.0,0.0,4.574100e+07,0.0,0.0,0.0,0.0
25190,2020,Ukraine,213.909,0.000,-3.90,-8.670,0.0,4.891,0.000,0.61,...,0.0,0.0,0.0,0.0,0.0,4.373376e+07,0.0,0.0,0.0,0.0
25191,2020,United Arab Emirates,150.268,0.000,-2.54,-3.918,0.0,15.193,0.000,0.43,...,0.0,0.0,0.0,0.0,0.0,9.890400e+06,0.0,0.0,0.0,0.0
25192,2020,United Kingdom,329.579,0.000,-10.69,-39.431,0.0,4.855,0.000,0.95,...,0.0,0.0,0.0,0.0,0.0,6.788600e+07,0.0,0.0,0.0,0.0
25193,2020,United States,4712.771,0.000,-10.33,-543.046,0.0,14.238,0.000,13.54,...,0.0,0.0,0.0,0.0,0.0,3.310026e+08,0.0,0.0,0.0,0.0
25194,2020,Uruguay,5.840,0.000,-11.30,-0.744,0.0,1.681,0.000,0.02,...,0.0,0.0,0.0,0.0,0.0,3.473727e+06,0.0,0.0,0.0,0.0
25195,2020,Uzbekistan,112.784,0.000,-1.24,-1.415,0.0,3.370,0.000,0.32,...,0.0,0.0,0.0,0.0,0.0,3.346920e+07,0.0,0.0,0.0,0.0
25196,2020,Vanuatu,0.182,0.000,0.14,0.000,0.0,0.591,0.000,0.00,...,0.0,0.0,0.0,0.0,0.0,3.071500e+05,0.0,0.0,0.0,0.0
25197,2020,Venezuela,84.609,0.000,-14.69,-14.566,0.0,2.975,0.000,0.24,...,0.0,0.0,0.0,0.0,0.0,2.843594e+07,0.0,0.0,0.0,0.0
25198,2020,Vietnam,254.303,0.000,-2.31,-6.009,0.0,2.613,0.000,0.73,...,0.0,0.0,0.0,0.0,0.0,9.733858e+07,0.0,0.0,0.0,0.0
25199,2020,Wallis and Futuna,0.026,0.000,0.14,0.000,0.0,0.000,0.000,0.00,...,0.0,0.0,0.0,0.0,0.0,1.124600e+04,0.0,0.0,0.0,0.0
25200,2020,World,34807.259,34807.259,-5.16,-1895.244,0.0,4.465,4.465,100.00,...,0.0,0.0,0.0,0.0,0.0,7.794799e+09,0.0,0.0,0.0,0.0
25201,2020,Yemen,9.768,0.000,-2.52,-0.252,0.0,0.328,0.000,0.03,...,0.0,0.0,0.0,0.0,0.0,2.982597e+07,0.0,0.0,0.0,0.0
25202,2020,Zambia,6.573,0.000,-6.73,-0.474,0.0,0.358,0.000,0.02,...,0.0,0.0,0.0,0.0,0.0,1.838396e+07,0.0,0.0,0.0,0.0
25203,2020,Zimbabwe,10.531,0.000,-3.82,-0.418,0.0,0.709,0.000,0.03,...,0.0,0.0,0.0,0.0,0.0,1.486293e+07,0.0,0.0,0.0,0.0

In [7]:
# drop all data older than 1950
df3 = df2.drop(df2[df2.year < 1950].index)
df3.head(20)

,year,country,co2,consumption_co2,co2_growth_prct,co2_growth_abs,trade_co2,co2_per_capita,consumption_co2_per_capita,share_global_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
9028,1950,Afghanistan,0.084,0.0,475.00,0.070,0.0,0.011,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,7.752117e+06,9.421400e+09,0.0,0.0,0.0
9029,1950,Africa,93.452,0.0,20.86,16.129,0.0,0.474,0.0,1.56,...,0.0,0.0,0.0,0.0,0.0,2.277941e+08,0.000000e+00,0.0,0.0,0.0
9030,1950,Albania,0.297,0.0,-70.76,-0.718,0.0,0.235,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,1.263164e+06,1.958541e+09,0.0,0.0,0.0
9031,1950,Algeria,3.784,0.0,316.62,2.875,0.0,0.426,0.0,0.06,...,0.0,0.0,0.0,0.0,0.0,8.872250e+06,1.935055e+10,0.0,0.0,0.0
9032,1950,Angola,0.187,0.0,0.00,0.000,0.0,0.041,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,4.548021e+06,6.905244e+09,0.0,0.0,0.0
9033,1950,Argentina,29.921,0.0,94.74,14.557,0.0,1.756,0.0,0.50,...,0.0,0.0,0.0,0.0,0.0,1.703791e+07,1.363280e+11,0.0,0.0,0.0
9034,1950,Armenia,1.538,0.0,11.28,0.156,0.0,1.136,0.0,0.03,...,0.0,0.0,0.0,0.0,0.0,1.353502e+06,0.000000e+00,0.0,0.0,0.0
9035,1950,Aruba,0.410,0.0,25.24,0.000,0.0,10.764,0.0,0.01,...,0.0,0.0,0.0,0.0,0.0,3.805200e+04,0.000000e+00,0.0,0.0,0.0
9036,1950,Asia,476.122,0.0,4.24,19.386,0.0,0.341,0.0,7.93,...,0.0,0.0,0.0,0.0,0.0,1.404415e+09,0.000000e+00,0.0,0.0,0.0
9037,1950,Asia (excl. China & India),336.109,0.0,-1.47,-5.001,0.0,0.722,0.0,5.60,...,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0
9038,1950,Australia,54.739,0.0,45.40,17.092,0.0,6.694,0.0,0.91,...,0.0,0.0,0.0,0.0,0.0,8.177348e+06,9.767859e+10,0.0,0.0,0.0
9039,1950,Austria,20.894,0.0,-21.37,-5.680,0.0,3.012,0.0,0.35,...,0.0,0.0,0.0,0.0,0.0,6.936442e+06,4.096564e+10,0.0,0.0,0.0
9040,1950,Azerbaijan,8.918,0.0,11.33,0.907,0.0,3.046,0.0,0.15,...,0.0,0.0,0.0,0.0,0.0,2.927926e+06,0.000000e+00,0.0,0.0,0.0
9041,1950,Bahamas,0.055,0.0,0.00,0.000,0.0,0.695,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,7.909000e+04,0.000000e+00,0.0,0.0,0.0
9042,1950,Bahrain,1.381,0.0,-70.03,-3.228,0.0,11.948,0.0,0.02,...,0.0,0.0,0.0,0.0,0.0,1.156120e+05,3.851734e+08,0.0,0.0,0.0
9043,1950,Bangladesh,0.993,0.0,422.03,0.803,0.0,0.026,0.0,0.02,...,0.0,0.0,0.0,0.0,0.0,3.789467e+07,3.930118e+10,0.0,0.0,0.0
9044,1950,Barbados,0.073,0.0,1900.00,0.070,0.0,0.347,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,2.109900e+05,7.152900e+08,0.0,0.0,0.0
9045,1950,Belarus,18.768,0.0,11.41,1.922,0.0,2.423,0.0,0.31,...,0.0,0.0,0.0,0.0,0.0,7.745004e+06,0.000000e+00,0.0,0.0,0.0
9046,1950,Belgium,76.200,0.0,-5.66,-4.572,0.0,8.822,0.0,1.27,...,0.0,0.0,0.0,0.0,0.0,8.637521e+06,7.521435e+10,0.0,0.0,0.0
9047,1950,Belize,0.018,0.0,0.00,0.000,0.0,0.266,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,6.891500e+04,0.000000e+00,0.0,0.0,0.0

In [8]:
df3.columns

Index(['year', 'country', 'co2', 'consumption_co2', 'co2_growth_prct',
       'co2_growth_abs', 'trade_co2', 'co2_per_capita',
       'consumption_co2_per_capita', 'share_global_co2', 'cumulative_co2',
       'share_global_cumulative_co2', 'co2_per_gdp', 'consumption_co2_per_gdp',
       'co2_per_unit_energy', 'coal_co2', 'cement_co2', 'flaring_co2',
       'gas_co2', 'oil_co2', 'other_industry_co2', 'cement_co2_per_capita',
       'coal_co2_per_capita', 'flaring_co2_per_capita', 'gas_co2_per_capita',
       'oil_co2_per_capita', 'other_co2_per_capita', 'trade_co2_share',
       'share_global_cement_co2', 'share_global_coal_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_oil_co2', 'share_global_other_co2',
       'cumulative_cement_co2', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_oil_co2',
       'cumulative_other_co2', 'share_global_cumulative_cement_co2',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_oil_co2',
       'share_global_cumulative_other_co2', 'total_ghg', 'ghg_per_capita',
       'methane', 'methane_per_capita', 'nitrous_oxide',
       'nitrous_oxide_per_capita', 'population', 'gdp',
       'primary_energy_consumption', 'energy_per_capita', 'energy_per_gdp'],
      dtype='object')

In [10]:
# drop unused columns 
df4 = df3.drop(['consumption_co2',
    'co2_growth_prct',
    'co2_growth_abs',
    'trade_co2',
    'consumption_co2_per_capita',
    'share_global_co2',
    'cumulative_co2',
    'share_global_cumulative_co2',
    'co2_per_gdp',
    'consumption_co2_per_gdp',
    'cement_co2_per_capita',
    'coal_co2_per_capita',
    'flaring_co2_per_capita',
    'gas_co2_per_capita',
    'oil_co2_per_capita',
    'other_co2_per_capita',
    'trade_co2_share',
    'share_global_cement_co2',
    'share_global_coal_co2',
    'share_global_flaring_co2',
    'share_global_gas_co2',
    'share_global_oil_co2',
    'share_global_other_co2',
    'cumulative_cement_co2',
    'cumulative_coal_co2',
    'cumulative_flaring_co2',
    'cumulative_gas_co2',
    'cumulative_oil_co2',
    'cumulative_other_co2',
    'share_global_cumulative_cement_co2',
    'share_global_cumulative_coal_co2',
    'share_global_cumulative_flaring_co2',
    'share_global_cumulative_gas_co2',
    'share_global_cumulative_oil_co2',
    'share_global_cumulative_other_co2',
    'population'], axis=1)
df4.head(20)

,year,country,co2,co2_per_capita,co2_per_unit_energy,coal_co2,cement_co2,flaring_co2,gas_co2,oil_co2,...,total_ghg,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
9028,1950,Afghanistan,0.084,0.011,0.0,0.021,0.000,0.0,0.000,0.063,...,0.0,0.0,0.0,0.0,0.0,0.0,9.421400e+09,0.0,0.0,0.0
9029,1950,Africa,93.452,0.474,0.0,68.711,2.014,0.0,0.004,22.723,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
9030,1950,Albania,0.297,0.235,0.0,0.043,0.007,0.0,0.000,0.246,...,0.0,0.0,0.0,0.0,0.0,0.0,1.958541e+09,0.0,0.0,0.0
9031,1950,Algeria,3.784,0.426,0.0,1.883,0.160,0.0,0.000,1.740,...,0.0,0.0,0.0,0.0,0.0,0.0,1.935055e+10,0.0,0.0,0.0
9032,1950,Angola,0.187,0.041,0.0,0.060,0.000,0.0,0.000,0.127,...,0.0,0.0,0.0,0.0,0.0,0.0,6.905244e+09,0.0,0.0,0.0
9033,1950,Argentina,29.921,1.756,0.0,3.561,0.778,0.0,0.000,25.582,...,0.0,0.0,0.0,0.0,0.0,0.0,1.363280e+11,0.0,0.0,0.0
9034,1950,Armenia,1.538,1.136,0.0,0.648,0.020,0.0,0.067,0.803,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
9035,1950,Aruba,0.410,10.764,0.0,0.000,0.000,0.0,0.000,0.410,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
9036,1950,Asia,476.122,0.341,0.0,305.201,6.325,0.0,5.465,159.131,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
9037,1950,Asia (excl. China & India),336.109,0.722,0.0,174.952,4.384,0.0,5.450,151.323,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
9038,1950,Australia,54.739,6.694,0.0,44.071,0.632,0.0,0.000,10.036,...,0.0,0.0,0.0,0.0,0.0,0.0,9.767859e+10,0.0,0.0,0.0
9039,1950,Austria,20.894,3.012,0.0,17.382,0.636,0.0,0.927,1.949,...,0.0,0.0,0.0,0.0,0.0,0.0,4.096564e+10,0.0,0.0,0.0
9040,1950,Azerbaijan,8.918,3.046,0.0,0.471,0.041,0.0,0.908,7.498,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
9041,1950,Bahamas,0.055,0.695,0.0,0.000,0.000,0.0,0.000,0.055,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
9042,1950,Bahrain,1.381,11.948,0.0,0.000,0.000,0.0,0.000,1.381,...,0.0,0.0,0.0,0.0,0.0,0.0,3.851734e+08,0.0,0.0,0.0
9043,1950,Bangladesh,0.993,0.026,0.0,0.498,0.002,0.0,0.000,0.493,...,0.0,0.0,0.0,0.0,0.0,0.0,3.930118e+10,0.0,0.0,0.0
9044,1950,Barbados,0.073,0.347,0.0,0.004,0.000,0.0,0.004,0.066,...,0.0,0.0,0.0,0.0,0.0,0.0,7.152900e+08,0.0,0.0,0.0
9045,1950,Belarus,18.768,2.423,0.0,5.972,0.118,0.0,0.320,12.357,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
9046,1950,Belgium,76.200,8.822,0.0,68.194,1.759,0.0,0.007,6.240,...,0.0,0.0,0.0,0.0,0.0,0.0,7.521435e+10,0.0,0.0,0.0
9047,1950,Belize,0.018,0.266,0.0,0.000,0.000,0.0,0.000,0.018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0

In [11]:
df4.dtypes

year                            int64
country                        object
co2                           float64
co2_per_capita                float64
co2_per_unit_energy           float64
coal_co2                      float64
cement_co2                    float64
flaring_co2                   float64
gas_co2                       float64
oil_co2                       float64
other_industry_co2            float64
total_ghg                     float64
ghg_per_capita                float64
methane                       float64
methane_per_capita            float64
nitrous_oxide                 float64
nitrous_oxide_per_capita      float64
gdp                           float64
primary_energy_consumption    float64
energy_per_capita             float64
energy_per_gdp                float64
dtype: object

In [12]:
# export dataframe to csv file
df4.to_csv(('co2_byYear_byCountry.csv'), index=False)